/* automatically generated by rust-bindgen 0.72.0 */

pub const ASSET_ALIGNMENT_MIN: u32 = 16;
unsafe extern "C" {
    pub fn __asset_init_compression_lvl2();
    pub fn __asset_init_compression_lvl3();
    pub fn asset_load(
        fn_: *const ::core::ffi::c_char,
        sz: *mut ::core::ffi::c_int,
    ) -> *mut ::core::ffi::c_void;
    pub fn asset_loadf(
        f: *mut crate::stdio::FILE,
        sz: *mut ::core::ffi::c_int,
    ) -> *mut ::core::ffi::c_void;
    pub fn asset_loadf_into(
        f: *mut crate::stdio::FILE,
        sz: *mut ::core::ffi::c_int,
        buf: *mut ::core::ffi::c_void,
        buf_size: *mut ::core::ffi::c_int,
    ) -> bool;
    pub fn asset_fopen(
        fn_: *const ::core::ffi::c_char,
        sz: *mut ::core::ffi::c_int,
    ) -> *mut crate::stdio::FILE;
    pub fn asset_loadfd(
        fd: ::core::ffi::c_int,
        sz: *mut ::core::ffi::c_int,
    ) -> *mut ::core::ffi::c_void;
    pub fn asset_loadfd_into(
        fd: ::core::ffi::c_int,
        sz: *mut ::core::ffi::c_int,
        buf: *mut ::core::ffi::c_void,
        buf_size: *mut ::core::ffi::c_int,
    ) -> bool;
    pub fn asset_fdopen(
        fd: ::core::ffi::c_int,
        sz: *mut ::core::ffi::c_int,
    ) -> *mut crate::stdio::FILE;
}
