/* automatically generated by rust-bindgen 0.72.0 */

pub type audio_fill_buffer_callback = ::core::option::Option<
    unsafe extern "C" fn(buffer: *mut ::core::ffi::c_short, numsamples: usize),
>;
unsafe extern "C" {
    pub fn audio_init(frequency: ::core::ffi::c_int, numbuffers: ::core::ffi::c_int);
    pub fn audio_set_buffer_callback(fill_buffer_callback: audio_fill_buffer_callback);
    pub fn audio_pause(pause: bool);
    pub fn audio_can_write() -> ::core::ffi::c_int;
    pub fn audio_write_silence();
    pub fn audio_close();
    pub fn audio_get_frequency() -> ::core::ffi::c_int;
    pub fn audio_get_buffer_length() -> ::core::ffi::c_int;
    pub fn audio_write_begin() -> *mut ::core::ffi::c_short;
    pub fn audio_write_end();
    pub fn audio_push(
        buffer: *const ::core::ffi::c_short,
        nsamples: ::core::ffi::c_int,
        blocking: bool,
    ) -> ::core::ffi::c_int;
    pub fn audio_write(buffer: *const ::core::ffi::c_short);
}
