/* automatically generated by rust-bindgen 0.72.0 */

pub const BB_RTC_TIMESTAMP_MIN: u32 = 946684800;
pub const BB_RTC_TIMESTAMP_MAX: u32 = 4102444799;
pub const BB_RTC_CENTURY_TIMESTAMP_MAX: u64 = 7258118399;
pub type time_t = ::core::ffi::c_longlong;
unsafe extern "C" {
    pub fn bb_rtc_get_time(out: *mut time_t) -> ::core::ffi::c_int;
    pub fn bb_rtc_set_time(new_time: time_t) -> ::core::ffi::c_int;
}
