/* automatically generated by rust-bindgen 0.72.0 */

pub const bbfs_error_e_BBFS_ERR_SUPERBLOCK: bbfs_error_e = -1;
pub type bbfs_error_e = ::core::ffi::c_int;
unsafe extern "C" {
    pub fn bbfs_init() -> ::core::ffi::c_int;
    pub fn bbfs_get_file_blocks(filename: *const ::core::ffi::c_char) -> *mut i16;
    pub fn bbfs_fsck(fix_errors: bool) -> ::core::ffi::c_int;
}
