/* automatically generated by rust-bindgen 0.72.0 */

unsafe extern "C" {
    pub fn bio_sensor_init();
    pub fn bio_sensor_close();
    pub fn bio_sensor_read_start(port: crate::joypad::joypad_port_t);
    pub fn bio_sensor_read_stop(port: crate::joypad::joypad_port_t);
    pub fn bio_sensor_get_active(port: crate::joypad::joypad_port_t) -> bool;
    pub fn bio_sensor_get_pulsing(port: crate::joypad::joypad_port_t) -> bool;
    pub fn bio_sensor_get_bpm(port: crate::joypad::joypad_port_t) -> ::core::ffi::c_int;
}
