/* automatically generated by rust-bindgen 0.72.0 */

pub const RENDER_MANUAL: u32 = 0;
pub const RENDER_AUTOMATIC: u32 = 1;
pub const CONSOLE_WIDTH: u32 = 64;
pub const CONSOLE_HEIGHT: u32 = 28;
pub const TAB_WIDTH: u32 = 4;
pub const HORIZONTAL_PADDING: u32 = 64;
pub const VERTICAL_PADDING: u32 = 8;
unsafe extern "C" {
    pub fn console_init();
    pub fn console_close();
    pub fn console_set_debug(debug: bool);
    pub fn console_set_render_mode(mode: ::core::ffi::c_int);
    pub fn console_clear();
    pub fn console_render();
}
