/* automatically generated by rust-bindgen 0.72.0 */

unsafe extern "C" {
    pub fn cpak_read(
        port: crate::joypad::joypad_port_t,
        bank: u8,
        address: u16,
        buffer: *mut ::core::ffi::c_void,
        len: usize,
    ) -> ::core::ffi::c_int;
    pub fn cpak_write(
        port: crate::joypad::joypad_port_t,
        bank: u8,
        address: u16,
        buffer: *const ::core::ffi::c_void,
        len: usize,
    ) -> ::core::ffi::c_int;
    pub fn cpak_supports_bankswitching(port: crate::joypad::joypad_port_t) -> bool;
    pub fn cpak_probe_banks(port: crate::joypad::joypad_port_t) -> ::core::ffi::c_int;
}
