/* automatically generated by rust-bindgen 0.72.0 */

pub const DD_ASIC_BASE: u32 = 83887360;
pub const DD_ASIC_DATA: u32 = 83887360;
pub const DD_ASIC_STATUS: u32 = 83887368;
pub const DD_ASIC_WCMD: u32 = 83887368;
pub const DD_ASIC_WCTRL: u32 = 83887376;
pub const DD_RTC_TIMESTAMP_MIN: u32 = 820454400;
pub const DD_RTC_TIMESTAMP_MAX: u32 = 3976214399;
pub const dd_cmd_t_DD_CMD_CLEAR_RESET_FLAG: dd_cmd_t = 9;
pub const dd_cmd_t_DD_CMD_RTC_SET_YEARMONTH: dd_cmd_t = 15;
pub const dd_cmd_t_DD_CMD_RTC_SET_DAYHOUR: dd_cmd_t = 16;
pub const dd_cmd_t_DD_CMD_RTC_SET_MINSEC: dd_cmd_t = 17;
pub const dd_cmd_t_DD_CMD_RTC_GET_YEARMONTH: dd_cmd_t = 18;
pub const dd_cmd_t_DD_CMD_RTC_GET_DAYHOUR: dd_cmd_t = 19;
pub const dd_cmd_t_DD_CMD_RTC_GET_MINSEC: dd_cmd_t = 20;
pub type dd_cmd_t = ::core::ffi::c_uint;
pub type time_t = ::core::ffi::c_longlong;
unsafe extern "C" {
    pub static mut dd_found: bool;
    pub fn dd_write(address: u32, value: u16);
    pub fn dd_read(address: u32) -> u16;
    pub fn dd_command(cmd: dd_cmd_t) -> u16;
    pub fn dd_rtc_get_time(out: *mut time_t) -> ::core::ffi::c_int;
    pub fn dd_rtc_set_time(new_time: time_t) -> ::core::ffi::c_int;
}
