/* automatically generated by rust-bindgen 0.72.0 */

pub const DEBUG_FEATURE_LOG_USB: u32 = 1;
pub const DEBUG_FEATURE_LOG_ISVIEWER: u32 = 2;
pub const DEBUG_FEATURE_LOG_SD: u32 = 4;
pub const DEBUG_FEATURE_FILE_SD: u32 = 8;
pub const DEBUG_FEATURE_ALL: u32 = 255;
unsafe extern "C" {
    pub fn debug_init_usblog() -> bool;
    pub fn debug_init_isviewer() -> bool;
    pub fn debug_init_sdlog(
        fn_: *const ::core::ffi::c_char,
        openfmt: *const ::core::ffi::c_char,
    ) -> bool;
    pub fn debug_init_sdfs(prefix: *const ::core::ffi::c_char, npart: ::core::ffi::c_int) -> bool;
    pub fn debug_close_sdfs();
    pub fn debug_hexdump(buffer: *const ::core::ffi::c_void, size: ::core::ffi::c_int);
    pub fn debug_backtrace();
    pub fn debug_assert_func_f(
        file: *const ::core::ffi::c_char,
        line: ::core::ffi::c_int,
        func: *const ::core::ffi::c_char,
        failedexpr: *const ::core::ffi::c_char,
        msg: *const ::core::ffi::c_char,
        ...
    ) -> !;
}
