/* automatically generated by rust-bindgen 0.72.0 */

unsafe extern "C" {
    pub fn dma_write_raw_async(
        ram_address: *const ::core::ffi::c_void,
        pi_address: ::core::ffi::c_ulong,
        len: ::core::ffi::c_ulong,
    );
    pub fn dma_write(
        ram_address: *const ::core::ffi::c_void,
        pi_address: ::core::ffi::c_ulong,
        len: ::core::ffi::c_ulong,
    );
    pub fn dma_read_raw_async(
        ram_address: *mut ::core::ffi::c_void,
        pi_address: ::core::ffi::c_ulong,
        len: ::core::ffi::c_ulong,
    );
    pub fn dma_read_async(
        ram_pointer: *mut ::core::ffi::c_void,
        pi_address: ::core::ffi::c_ulong,
        len: ::core::ffi::c_ulong,
    );
    pub fn dma_read(
        ram_address: *mut ::core::ffi::c_void,
        pi_address: ::core::ffi::c_ulong,
        len: ::core::ffi::c_ulong,
    );
    pub fn dma_wait();
    pub fn io_read(pi_address: u32) -> u32;
    pub fn io_write(pi_address: u32, data: u32);
    pub fn io_accessible(pi_address: u32) -> bool;
    pub fn dma_busy() -> ::core::ffi::c_int;
}
