/* automatically generated by rust-bindgen 0.72.0 */

pub const EEPROM_BLOCK_SIZE: u32 = 8;
pub const eeprom_type_t_EEPROM_NONE: eeprom_type_t = 0;
pub const eeprom_type_t_EEPROM_4K: eeprom_type_t = 1;
pub const eeprom_type_t_EEPROM_16K: eeprom_type_t = 2;
pub type eeprom_type_t = ::core::ffi::c_uint;
unsafe extern "C" {
    pub fn eeprom_present() -> eeprom_type_t;
    pub fn eeprom_total_blocks() -> usize;
    pub fn eeprom_read(block: u8, dest: *mut u8);
    pub fn eeprom_write(block: u8, src: *const u8) -> u8;
    pub fn eeprom_read_bytes(dest: *mut u8, start: usize, len: usize);
    pub fn eeprom_write_bytes(src: *const u8, start: usize, len: usize);
}
