/* automatically generated by rust-bindgen 0.72.0 */

pub const eia608_channel_t_EIA608_CC1: eia608_channel_t = 1;
pub const eia608_channel_t_EIA608_CC2: eia608_channel_t = 2;
pub type eia608_channel_t = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct eia608_captionparms_t {
    pub row: ::core::ffi::c_int,
    pub underline: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of eia608_captionparms_t"][::core::mem::size_of::<eia608_captionparms_t>() - 8usize];
    ["Alignment of eia608_captionparms_t"]
        [::core::mem::align_of::<eia608_captionparms_t>() - 4usize];
    ["Offset of field: eia608_captionparms_t::row"]
        [::core::mem::offset_of!(eia608_captionparms_t, row) - 0usize];
    ["Offset of field: eia608_captionparms_t::underline"]
        [::core::mem::offset_of!(eia608_captionparms_t, underline) - 4usize];
};
pub const eia608_ctrl_t_EIA608_NOP: eia608_ctrl_t = 32896;
pub const eia608_ctrl_t_EAI608_CC1_TS: eia608_ctrl_t = 37305;
pub const eia608_ctrl_t_EAI608_CC2_TS: eia608_ctrl_t = 6585;
pub const eia608_ctrl_t_EIA608_CC1_RCL: eia608_ctrl_t = 37920;
pub const eia608_ctrl_t_EIA608_CC2_RCL: eia608_ctrl_t = 7200;
pub const eia608_ctrl_t_EIA608_CC1_BS: eia608_ctrl_t = 38049;
pub const eia608_ctrl_t_EIA608_CC2_BS: eia608_ctrl_t = 7329;
pub const eia608_ctrl_t_EIA608_CC1_AOF: eia608_ctrl_t = 38050;
pub const eia608_ctrl_t_EIA608_CC2_AOF: eia608_ctrl_t = 7330;
pub const eia608_ctrl_t_EIA608_CC1_AON: eia608_ctrl_t = 37923;
pub const eia608_ctrl_t_EIA608_CC2_AON: eia608_ctrl_t = 7203;
pub const eia608_ctrl_t_EIA608_CC1_DER: eia608_ctrl_t = 38052;
pub const eia608_ctrl_t_EIA608_CC2_DER: eia608_ctrl_t = 7332;
pub const eia608_ctrl_t_EIA608_CC1_RU2: eia608_ctrl_t = 37925;
pub const eia608_ctrl_t_EIA608_CC2_RU2: eia608_ctrl_t = 7205;
pub const eia608_ctrl_t_EIA608_CC1_RU3: eia608_ctrl_t = 37926;
pub const eia608_ctrl_t_EIA608_CC2_RU3: eia608_ctrl_t = 7206;
pub const eia608_ctrl_t_EIA608_CC1_RU4: eia608_ctrl_t = 38055;
pub const eia608_ctrl_t_EIA608_CC2_RU4: eia608_ctrl_t = 7335;
pub const eia608_ctrl_t_EIA608_CC1_FON: eia608_ctrl_t = 38056;
pub const eia608_ctrl_t_EIA608_CC2_FON: eia608_ctrl_t = 7336;
pub const eia608_ctrl_t_EIA608_CC1_RDC: eia608_ctrl_t = 37929;
pub const eia608_ctrl_t_EIA608_CC2_RDC: eia608_ctrl_t = 7209;
pub const eia608_ctrl_t_EIA608_CC1_TR: eia608_ctrl_t = 37930;
pub const eia608_ctrl_t_EIA608_CC2_TR: eia608_ctrl_t = 7210;
pub const eia608_ctrl_t_EIA608_CC1_RTD: eia608_ctrl_t = 38059;
pub const eia608_ctrl_t_EIA608_CC2_RTD: eia608_ctrl_t = 7339;
pub const eia608_ctrl_t_EIA608_CC1_EDM: eia608_ctrl_t = 37932;
pub const eia608_ctrl_t_EIA608_CC2_EDM: eia608_ctrl_t = 7212;
pub const eia608_ctrl_t_EIA608_CC1_CR: eia608_ctrl_t = 38061;
pub const eia608_ctrl_t_EIA608_CC2_CR: eia608_ctrl_t = 7341;
pub const eia608_ctrl_t_EIA608_CC1_ENM: eia608_ctrl_t = 38062;
pub const eia608_ctrl_t_EIA608_CC2_ENM: eia608_ctrl_t = 7342;
pub const eia608_ctrl_t_EIA608_CC1_EOC: eia608_ctrl_t = 37935;
pub const eia608_ctrl_t_EIA608_CC2_EOC: eia608_ctrl_t = 7215;
pub const eia608_ctrl_t_EIA608_CC1_TO1: eia608_ctrl_t = 38817;
pub const eia608_ctrl_t_EIA608_CC2_TO1: eia608_ctrl_t = 8097;
pub const eia608_ctrl_t_EIA608_CC1_TO2: eia608_ctrl_t = 38818;
pub const eia608_ctrl_t_EIA608_CC2_TO2: eia608_ctrl_t = 8098;
pub const eia608_ctrl_t_EIA608_CC1_TO3: eia608_ctrl_t = 38691;
pub const eia608_ctrl_t_EIA608_CC2_TO3: eia608_ctrl_t = 7971;
pub type eia608_ctrl_t = ::core::ffi::c_uint;
unsafe extern "C" {
    pub fn eia608_init();
    pub fn eia608_close();
    pub fn eia608_start();
    pub fn eia608_stop();
    pub fn eia608_write_raw(data: u16, calc_parity: bool) -> bool;
    pub fn eia608_write_ctrl_raw(ctrl: eia608_ctrl_t);
    pub fn eia608_caption_prepare(
        cc: eia608_channel_t,
        utf8_str: *const ::core::ffi::c_char,
        parms: *mut eia608_captionparms_t,
    );
    pub fn eia608_caption_show(cc: eia608_channel_t, duration_secs: f32);
}
