/* automatically generated by rust-bindgen 0.72.0 */

pub const FM_EPSILON: f64 = 0.0001;
pub const FM_PI: f64 = 3.14159265358979;
unsafe extern "C" {
    pub fn fm_sinf(x: f32) -> f32;
    pub fn fm_sinf_approx(x: f32, approx: ::core::ffi::c_int) -> f32;
    pub fn fm_cosf(x: f32) -> f32;
    pub fn fm_sincosf(x: f32, sin: *mut f32, cos: *mut f32);
    pub fn fm_atan2f(y: f32, x: f32) -> f32;
    pub fn fm_exp(x: f32) -> f32;
    pub fn fm_lerp_angle(a: f32, b: f32, t: f32) -> f32;
    pub fn fm_wrap_angle(angle: f32) -> f32;
}
