/* automatically generated by rust-bindgen 0.72.0 */

unsafe extern "C" {
    pub fn ioctl(
        fd: ::core::ffi::c_int,
        cmd: ::core::ffi::c_ulong,
        argp: *mut ::core::ffi::c_void,
    ) -> ::core::ffi::c_int;
}
