/* automatically generated by rust-bindgen 0.72.0 */

pub const joybus_accessory_io_status_t_JOYBUS_ACCESSORY_IO_STATUS_OK: joybus_accessory_io_status_t =
    0;
pub const joybus_accessory_io_status_t_JOYBUS_ACCESSORY_IO_STATUS_NO_DEVICE:
    joybus_accessory_io_status_t = -1;
pub const joybus_accessory_io_status_t_JOYBUS_ACCESSORY_IO_STATUS_NO_PAK:
    joybus_accessory_io_status_t = -2;
pub const joybus_accessory_io_status_t_JOYBUS_ACCESSORY_IO_STATUS_BAD_CRC:
    joybus_accessory_io_status_t = -3;
pub type joybus_accessory_io_status_t = ::core::ffi::c_int;
unsafe extern "C" {
    pub fn joybus_accessory_read(
        port: ::core::ffi::c_int,
        addr: u16,
        data: *mut u8,
    ) -> ::core::ffi::c_int;
    pub fn joybus_accessory_write(
        port: ::core::ffi::c_int,
        addr: u16,
        data: *const u8,
    ) -> ::core::ffi::c_int;
}
