/* automatically generated by rust-bindgen 0.72.0 */

pub const JOYBUS_BLOCK_SIZE: u32 = 64;
pub const JOYBUS_ACCESSORY_DATA_SIZE: u32 = 32;
pub const JOYBUS_PORT_COUNT: u32 = 5;
pub const JOYBUS_IDENTIFIER_UNKNOWN: u32 = 0;
pub const JOYBUS_IDENTIFIER_NONE: u32 = 65535;
pub const JOYBUS_IDENTIFIER_N64_VOICE_RECOGNITION: u32 = 1;
pub const JOYBUS_IDENTIFIER_N64_RANDNET_KEYBOARD: u32 = 2;
pub const JOYBUS_IDENTIFIER_64GB_LINK_CABLE: u32 = 3;
pub const JOYBUS_IDENTIFIER_GBA_LINK_CABLE: u32 = 4;
pub const JOYBUS_IDENTIFIER_CART_RTC: u32 = 16;
pub const JOYBUS_IDENTIFIER_CART_EEPROM_4KBIT: u32 = 128;
pub const JOYBUS_IDENTIFIER_CART_EEPROM_16KBIT: u32 = 192;
pub const JOYBUS_IDENTIFIER_N64_CONTROLLER: u32 = 1280;
pub const JOYBUS_IDENTIFIER_N64_MOUSE: u32 = 512;
pub const JOYBUS_IDENTIFIER_MASK_PLATFORM: u32 = 6144;
pub const JOYBUS_IDENTIFIER_PLATFORM_GCN: u32 = 2048;
pub const JOYBUS_IDENTIFIER_MASK_GCN_CONTROLLER: u32 = 256;
pub const JOYBUS_IDENTIFIER_MASK_GCN_NORUMBLE: u32 = 8192;
pub const JOYBUS_IDENTIFIER_MASK_GCN_WIRELESS: u32 = 32768;
pub const JOYBUS_IDENTIFY_STATUS_ACCESSORY_MASK: u32 = 3;
pub const JOYBUS_IDENTIFY_STATUS_ACCESSORY_UNSUPPORTED: u32 = 0;
pub const JOYBUS_IDENTIFY_STATUS_ACCESSORY_PRESENT: u32 = 1;
pub const JOYBUS_IDENTIFY_STATUS_ACCESSORY_ABSENT: u32 = 2;
pub const JOYBUS_IDENTIFY_STATUS_ACCESSORY_CHANGED: u32 = 3;
pub const JOYBUS_IDENTIFY_STATUS_VOICE_RECOGNITON_READY: u32 = 1;
pub const JOYBUS_IDENTIFY_STATUS_COMMAND_CHECKSUM_ERROR: u32 = 4;
pub const JOYBUS_IDENTIFY_STATUS_GCN_RUMBLE_ACTIVE: u32 = 8;
pub const JOYBUS_IDENTIFY_STATUS_EEPROM_BUSY: u32 = 128;
pub type joybus_identifier_t = u16;
pub type joybus_callback_t = ::core::option::Option<
    unsafe extern "C" fn(out_dwords: *mut u64, ctx: *mut ::core::ffi::c_void),
>;
unsafe extern "C" {
    pub fn joybus_exec_async(
        input: *const ::core::ffi::c_void,
        callback: joybus_callback_t,
        ctx: *mut ::core::ffi::c_void,
    );
    pub fn joybus_exec(input: *const ::core::ffi::c_void, output: *mut ::core::ffi::c_void);
}
