/* automatically generated by rust-bindgen 0.72.0 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct kcond_s {
    _unused: [u8; 0],
}
pub type kcond_t = kcond_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct kirq_wait_t {
    pub counter: i64,
    pub cond: *mut kcond_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kirq_wait_t"][::core::mem::size_of::<kirq_wait_t>() - 16usize];
    ["Alignment of kirq_wait_t"][::core::mem::align_of::<kirq_wait_t>() - 8usize];
    ["Offset of field: kirq_wait_t::counter"]
        [::core::mem::offset_of!(kirq_wait_t, counter) - 0usize];
    ["Offset of field: kirq_wait_t::cond"][::core::mem::offset_of!(kirq_wait_t, cond) - 8usize];
};
unsafe extern "C" {
    pub fn kirq_begin_wait_sp() -> kirq_wait_t;
    pub fn kirq_begin_wait_dp() -> kirq_wait_t;
    pub fn kirq_begin_wait_si() -> kirq_wait_t;
    pub fn kirq_begin_wait_ai() -> kirq_wait_t;
    pub fn kirq_begin_wait_vi() -> kirq_wait_t;
    pub fn kirq_begin_wait_pi() -> kirq_wait_t;
    pub fn kirq_wait(wait: *mut kirq_wait_t);
}
