/* automatically generated by rust-bindgen 0.72.0 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct yuv_frame_s {
    _unused: [u8; 0],
}
pub type yuv_frame_t = yuv_frame_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpeg2_s {
    _unused: [u8; 0],
}
pub type mpeg2_t = mpeg2_s;
unsafe extern "C" {
    pub fn mpeg2_open(fn_: *const ::core::ffi::c_char) -> *mut mpeg2_t;
    pub fn mpeg2_get_framerate(mp2: *mut mpeg2_t) -> f32;
    pub fn mpeg2_get_width(mp2: *mut mpeg2_t) -> ::core::ffi::c_int;
    pub fn mpeg2_get_height(mp2: *mut mpeg2_t) -> ::core::ffi::c_int;
    pub fn mpeg2_next_frame(mp2: *mut mpeg2_t) -> bool;
    pub fn mpeg2_get_frame(mp2: *mut mpeg2_t) -> yuv_frame_t;
    pub fn mpeg2_rewind(mp2: *mut mpeg2_t);
    pub fn mpeg2_close(mp2: *mut mpeg2_t);
}
