/* automatically generated by rust-bindgen 0.72.0 */

unsafe extern "C" {
    pub fn pixelfx_send_game_id(rom_check_code: u64, media_format: u8, region_code: u8);
    pub fn pixelfx_clear_game_id();
}
