/* automatically generated by rust-bindgen 0.72.0 */

unsafe extern "C" {
    pub fn rdpq_sprite_upload(
        tile: crate::rdpq::rdpq_tile_t,
        sprite: *mut crate::sprite::sprite_t,
        parms: *const crate::rdpq_tex::rdpq_texparms_t,
    ) -> ::core::ffi::c_int;
    pub fn rdpq_sprite_blit(
        sprite: *mut crate::sprite::sprite_t,
        x0: f32,
        y0: f32,
        parms: *const crate::rdpq_tex::rdpq_blitparms_t,
    );
}
