/* automatically generated by rust-bindgen 0.72.0 */

unsafe extern "C" {
    pub fn rdpq_attach(
        surf_color: *const crate::surface::surface_t,
        surf_z: *const crate::surface::surface_t,
    );
    pub fn rdpq_attach_clear(
        surf_color: *const crate::surface::surface_t,
        surf_z: *const crate::surface::surface_t,
    );
    pub fn __rdpq_clear(color: *const crate::graphics::color_t);
    pub fn __rdpq_clear_z(z: *const u16);
    pub fn rdpq_is_attached() -> bool;
    pub fn rdpq_detach_show();
    pub fn rdpq_detach_cb(
        cb: ::core::option::Option<unsafe extern "C" fn(arg1: *mut ::core::ffi::c_void)>,
        arg: *mut ::core::ffi::c_void,
    );
    pub fn rdpq_get_attached() -> *const crate::surface::surface_t;
}
