/* automatically generated by rust-bindgen 0.72.0 */

unsafe extern "C" {
    pub fn rdpq_debug_start();
    pub fn rdpq_debug_stop();
    pub fn rdpq_debug_log(show_log: bool);
    pub fn rdpq_debug_log_msg(str_: *const ::core::ffi::c_char);
    pub fn rdpq_debug_get_tmem() -> crate::surface::surface_t;
    pub fn rdpq_debug_install_hook(
        hook: ::core::option::Option<
            unsafe extern "C" fn(
                ctx: *mut ::core::ffi::c_void,
                cmd: *mut u64,
                cmd_size: ::core::ffi::c_int,
            ),
        >,
        ctx: *mut ::core::ffi::c_void,
    );
    pub fn rdpq_debug_disasm(buf: *mut u64, out: *mut crate::stdio::FILE) -> bool;
    pub fn rdpq_debug_disasm_size(buf: *mut u64) -> ::core::ffi::c_int;
    pub fn rdpq_debug_disasm_cc(cc64: u64) -> *mut ::core::ffi::c_char;
}
