/* automatically generated by rust-bindgen 0.72.0 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rdpq_matdb_s {
    _unused: [u8; 0],
}
pub type rdpq_matdb_t = rdpq_matdb_s;
pub type rdpq_mat_t = *mut ::core::ffi::c_void;
unsafe extern "C" {
    pub fn __rdpq_mat_ext_get_bool(mat: *mut rdpq_mat_t, ext_key: u32, value: *mut bool) -> bool;
    pub fn __rdpq_mat_ext_get_int(mat: *mut rdpq_mat_t, ext_key: u32, value: *mut u32) -> bool;
    pub fn __rdpq_mat_ext_get_string(
        mat: *mut rdpq_mat_t,
        ext_key: u32,
        value: *mut *mut ::core::ffi::c_char,
    ) -> bool;
    pub fn __rdpq_mat_ext_get_float(mat: *mut rdpq_mat_t, ext_key: u32, value: *mut f32) -> bool;
    pub fn rdpq_matdb_open(filename: *const ::core::ffi::c_char) -> *mut rdpq_matdb_t;
    pub fn rdpq_matdb_close(mdb: *mut rdpq_matdb_t);
    pub fn rdpq_matdb_load(
        mdb: *mut rdpq_matdb_t,
        mat_name: *const ::core::ffi::c_char,
    ) -> *mut rdpq_mat_t;
    pub fn rdpq_mat_load_buf(
        buf: *mut ::core::ffi::c_void,
        size: ::core::ffi::c_int,
    ) -> *mut rdpq_mat_t;
    pub fn rdpq_mat_draw_begin(mat: *mut rdpq_mat_t);
    pub fn rdpq_mat_draw_end(mat: *mut rdpq_mat_t);
    pub fn rdpq_mat_free(mat: *mut rdpq_mat_t);
    pub fn rdpq_mat_set_texture_path(path: *const ::core::ffi::c_char);
}
