/* automatically generated by rust-bindgen 0.72.0 */

pub const USE_OSRAW: u32 = 0;
pub const DEBUG_ADDRESS_SIZE: u32 = 8388608;
pub const CHECK_EMULATOR: u32 = 0;
pub const CART_NONE: u32 = 0;
pub const CART_64DRIVE: u32 = 1;
pub const CART_EVERDRIVE: u32 = 2;
pub const CART_SC64: u32 = 3;
pub const DATATYPE_TEXT: u32 = 1;
pub const DATATYPE_RAWBINARY: u32 = 2;
pub const DATATYPE_HEADER: u32 = 3;
pub const DATATYPE_SCREENSHOT: u32 = 4;
pub const DATATYPE_HEARTBEAT: u32 = 5;
pub const DATATYPE_RDBPACKET: u32 = 6;
unsafe extern "C" {
    pub fn usb_initialize() -> ::core::ffi::c_char;
    pub fn usb_getcart() -> ::core::ffi::c_char;
    pub fn usb_write(
        datatype: ::core::ffi::c_int,
        data: *const ::core::ffi::c_void,
        size: ::core::ffi::c_int,
    ) -> ::core::ffi::c_char;
    pub fn usb_poll() -> ::core::ffi::c_ulong;
    pub fn usb_read(buffer: *mut ::core::ffi::c_void, size: ::core::ffi::c_int);
    pub fn usb_skip(nbytes: ::core::ffi::c_int);
    pub fn usb_rewind(nbytes: ::core::ffi::c_int);
    pub fn usb_purge();
    pub fn usb_timedout() -> ::core::ffi::c_char;
    pub fn usb_sendheartbeat();
}
